# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/multi-nlpgame/ # 프로젝트 이름
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: startapp.sh
      timeout: 180
      runas: ec2-user
